### ISSUE TITLE
Better handling of ClientErrors

### ISSUE THREAD

**Issue by mwildehahn** [remind101/stacker#242]
Right now when we have CF errors we blow up:

```
Traceback (most recent call last):
  File "/Users/mhahn/.virtualenvs/stacker/bin/stacker", line 4, in <module>
    __import__('pkg_resources').run_script('stacker==0.8.1', 'stacker')
  File "/Users/mhahn/.virtualenvs/stacker/lib/python2.7/site-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/mhahn/.virtualenvs/stacker/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/mhahn/.virtualenvs/stacker/lib/python2.7/site-packages/stacker-0.8.1-py2.7.egg/EGG-INFO/scripts/stacker", line 9, in <module>

  File "build/bdist.macosx-10.10-x86_64/egg/stacker/commands/stacker/build.py", line 52, in run
  File "build/bdist.macosx-10.10-x86_64/egg/stacker/actions/base.py", line 125, in execute
  File "build/bdist.macosx-10.10-x86_64/egg/stacker/actions/build.py", line 311, in run
  File "build/bdist.macosx-10.10-x86_64/egg/stacker/plan.py", line 251, in execute
  File "build/bdist.macosx-10.10-x86_64/egg/stacker/plan.py", line 219, in _single_run
  File "build/bdist.macosx-10.10-x86_64/egg/stacker/plan.py", line 72, in run
  File "build/bdist.macosx-10.10-x86_64/egg/stacker/actions/build.py", line 229, in _launch_stack
  File "build/bdist.macosx-10.10-x86_64/egg/stacker/providers/aws/default.py", line 230, in update_stack
  File "build/bdist.macosx-10.10-x86_64/egg/stacker/providers/aws/default.py", line 71, in retry_on_throttling
  File "build/bdist.macosx-10.10-x86_64/egg/stacker/util.py", line 58, in retry_with_backoff
  File "/Users/mhahn/.virtualenvs/stacker/lib/python2.7/site-packages/botocore-1.4.56-py2.7.egg/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/mhahn/.virtualenvs/stacker/lib/python2.7/site-packages/botocore-1.4.56-py2.7.egg/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the UpdateStack operation: Stack:arn:aws:cloudformation:us-east-1:935008130000:stack/mh-empire-dev-elasticsearch/f0988da0-8cce-11e6-883d-500c219ab02a is in UPDATE_ROLLBACK_IN_PROGRESS state and can not be updated.
```

we should clean this up

**Comment by phobologic** [comment]
This was handled for the most common issues we hit in https://github.com/remind101/stacker/pull/473, closing.
