### ISSUE TITLE
Can't run a diff

### ISSUE THREAD

**Issue by russ** [remind101/stacker#244]
I'm just upgraded to the latest version of stacker and I'm trying to run a diff but getting an error.

```
stacker diff empire.env empire.yaml 
[2016-10-12T10:59:29] Using Default AWS Provider
[2016-10-12T10:59:29] Diffing stacks: empire-vpc, empire-empireDB, empire-empireMinion, empire-stanDB, empire-bastion, empire-empireController
[2016-10-12T10:59:29] Plan Status:
[2016-10-12T10:59:29]   empire-vpc:              pending
[2016-10-12T10:59:29]   empire-empireDB:         pending
[2016-10-12T10:59:29]   empire-empireMinion:     pending
[2016-10-12T10:59:29]   empire-stanDB:           pending
[2016-10-12T10:59:29]   empire-bastion:          pending
[2016-10-12T10:59:29]   empire-empireController: pending
============== Stack: vpc ==============
*** No changes to template ***
Traceback (most recent call last):
  File "/usr/local/bin/stacker", line 4, in <module>
    __import__('pkg_resources').run_script('stacker==0.8.1', 'stacker')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/stacker-0.8.1-py2.7.egg/EGG-INFO/scripts/stacker", line 9, in <module>
    
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/commands/stacker/diff.py", line 32, in run
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/actions/base.py", line 125, in execute
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/actions/diff.py", line 203, in run
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/plan.py", line 251, in execute
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/plan.py", line 219, in _single_run
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/plan.py", line 72, in run
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/actions/diff.py", line 168, in _diff_stack
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/blueprints/base.py", line 392, in rendered
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/blueprints/base.py", line 383, in render_template
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/blueprints/empire/empire_base.py", line 50, in create_template
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/blueprints/empire/empire_minion.py", line 186, in create_iam_profile
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/blueprints/empire/empire_minion.py", line 166, in generate_iam_policies
  File "build/bdist.macosx-10.11-x86_64/egg/stacker/blueprints/empire/policies.py", line 19, in ecs_agent_policy
AttributeError: 'module' object has no attribute 'ECSAction'
```

I upgraded from version 0.5.2 to 0.8.1

**Comment by russ** [comment]
Nevermind. Somehow had some old awacs package lying around causing that issue.
