### ISSUE TITLE
import module failing

### ISSUE THREAD

**Issue by ct-wn** [remind101/stacker#299]
Hello,

I am encountering the same issue no matter how I run stacker. I have had the most success using docker but I can't get past this issue now. I have tried a custom vpc template I created as well as the example blueprint but the furthest I can get is to this error:

docker run -it -e AWS_ACCESS_KEY_ID=**** -e AWS_SECRET_ACCESS_KEY=**** -v `pwd`:/stacker remind101/stacker build -v -v /stacker/conf/env.yml /stacker/conf/dev.yml

[2017-01-19T23:26:04] DEBUG stacker.actions.build:208(_launch_stack): Resolving stack vpc
Traceback (most recent call last):
  File "/usr/local/bin/stacker", line 4, in <module>
    __import__('pkg_resources').run_script('stacker==1.0.0a5', 'stacker')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/stacker-1.0.0a5-py2.7.egg/EGG-INFO/scripts/stacker", line 9, in <module>

  File "build/bdist.linux-x86_64/egg/stacker/commands/stacker/build.py", line 52, in run
  File "build/bdist.linux-x86_64/egg/stacker/actions/base.py", line 125, in execute
  File "build/bdist.linux-x86_64/egg/stacker/actions/build.py", line 283, in run
  File "build/bdist.linux-x86_64/egg/stacker/plan.py", line 267, in execute
  File "build/bdist.linux-x86_64/egg/stacker/plan.py", line 227, in _single_run
  File "build/bdist.linux-x86_64/egg/stacker/plan.py", line 74, in run
  File "build/bdist.linux-x86_64/egg/stacker/actions/build.py", line 209, in _launch_stack
  File "build/bdist.linux-x86_64/egg/stacker/stack.py", line 165, in resolve
  File "build/bdist.linux-x86_64/egg/stacker/stack.py", line 122, in blueprint
  File "build/bdist.linux-x86_64/egg/stacker/util.py", line 258, in load_object_from_string
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 30, in import_module
    raise TypeError("relative imports require the 'package' argument")
TypeError: relative imports require the 'package' argument

**Comment by phobologic** [comment]
Can you share the config that you're using for this?  Most specifically for the vpc stack?

**Comment by ct-wn** [comment]
This happens with the ones from the blueprints repo
https://github.com/remind101/stacker_blueprints/blob/release-1.0/stacker_blueprints/vpc.py

**Comment by phobologic** [comment]
Hey @ct-wn - I mean what config file and environment file you are using that is causing this to break.  Also, where are you installing the blueprints you want to use? Is it relative to the path you're calling stacker from or is it installed (ie: via `python setup.py` or `pip install`)?

Thanks!

**Comment by ct-wn** [comment]
Hi Phobologic,

Here are the config / env files

[http://pastebin.com/ipKzf8cJ](http://pastebin.com/ipKzf8cJ)

This is the most recent command I ran that still failed (using the correct stacks path).

docker run -it -e AWS_ACCESS_KEY_ID='***' -e AWS_SECRET_ACCESS_KEY='***' -v `pwd`:/stacks remind101/stacker build -v conf/dev.env conf/dev.yml

The blueprints are relative to the path I'm calling stacker from.

├── conf
│   ├── dev.env
│   ├── dev.yml
│   └── prod.yml
└── stacker_blueprints
    └── vpc.py

**Comment by ct-wn** [comment]
I may have pasted the wrong version to pastebin, the classpath is actually:
class_path: ..stacker_blueprints.vpc.VPC

**Comment by phobologic** [comment]
Thanks - thsi is actually pretty common confusion, and something we're working on rectifying right now - getting people who are new to stacker started in the fastest way possible (a tutorial/example stack is almost complete).  So a few things:

Since you are not installing the blueprints in your `PYTHONPATH`, you need to tell stacker where to find the blueprint.  You can do that by adding the basedirectory for your blueprints to the `sys_path` setting like so: http://stacker.readthedocs.io/en/latest/config.html#module-paths

In your case you'd set in the top level of the config:

`sys_path: .`

Then, for the `class_path`, you'd use: `stacker_blueprints.vpc.VPC`.  Note, you'll need an `__init__.py` in the `stacker_blueprints` directory (it can be blank, but it's necessary with how python does imports).

 Let me know if that helps, thanks!

**Comment by ct-wn** [comment]
Thank you kindly that works a lot better, just have to deal with some template related errors now.
