### ISSUE TITLE
Error w/ invalid env var name (release-1.0)

### ISSUE THREAD

**Issue by phobologic** [remind101/stacker#301]
Testing out some changes I'm working on to the RDS blueprints, I accidentally had an error with one of the environment variables I was using in the config:

```
replica_replica_storage_encrypted
instead of
replica_storage_encrypted
```

That resulted in this error:

```
Traceback (most recent call last):
  File "/Users/mike/venv/trds/bin/stacker", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/mike/remind/repos/stacker/scripts/stacker", line 9, in <module>
    args.run(args)
  File "/Users/mike/remind/repos/stacker/stacker/commands/stacker/build.py", line 52, in run
    dump=options.dump)
  File "/Users/mike/remind/repos/stacker/stacker/actions/base.py", line 122, in execute
    self.run(*args, **kwargs)
  File "/Users/mike/remind/repos/stacker/stacker/actions/build.py", line 279, in run
    plan = self._generate_plan(tail=tail)
  File "/Users/mike/remind/repos/stacker/stacker/actions/build.py", line 243, in _generate_plan
    dependencies = self._get_dependencies()
  File "/Users/mike/remind/repos/stacker/stacker/actions/build.py", line 255, in _get_dependencies
    dependencies[stack.fqn] = stack.requires
  File "/Users/mike/remind/repos/stacker/stacker/stack.py", line 107, in requires
    d = deconstruct(lookup.input)
  File "/Users/mike/remind/repos/stacker/stacker/lookups/handlers/output.py", line 40, in deconstruct
    stack_name, output_name = value.split("::")
ValueError: need more than 1 value to unpack
```
Two things:

1. Why?
2. We should probably wrap the deconstruct call there in a try/except to let us know what variable is causing the issue.  Honestly, we could probably standardize this somehow as well, so we don't have to handle it in different parts of the code (`deconstruct` is used in various other places).

**Comment by ttaub** [comment]
Resolved #319
