### ISSUE TITLE
Empty environment parameter specified on command line causes stacker to fail

### ISSUE THREAD

**Issue by jonathanunderwood** [remind101/stacker#320]
Version: 1.0.0a6
A command such as:

```
stacker build -r eu-west-1 -t -e SomeVar= -e OtherVar=foo envfile.env stack.yaml
```

causes

```
Traceback (most recent call last):
  File "/usr/local/bin/stacker", line 9, in <module>
    args.run(args)
  File "/usr/local/lib/python2.7/site-packages/stacker/commands/stacker/build.py", line 52, in run
    dump=options.dump)
  File "/usr/local/lib/python2.7/site-packages/stacker/actions/base.py", line 125, in execute
    self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/stacker/actions/build.py", line 283, in run
    plan.execute()
  File "/usr/local/lib/python2.7/site-packages/stacker/plan.py", line 267, in execute
    if not self._single_run():
  File "/usr/local/lib/python2.7/site-packages/stacker/plan.py", line 227, in _single_run
    status = step.run()
  File "/usr/local/lib/python2.7/site-packages/stacker/plan.py", line 74, in run
    return self._run_func(self.stack, status=self.status)
  File "/usr/local/lib/python2.7/site-packages/stacker/actions/build.py", line 209, in _launch_stack
    stack.resolve(self.context, self.provider)
  File "/usr/local/lib/python2.7/site-packages/stacker/stack.py", line 156, in resolve
    self.blueprint.resolve_variables(self.variables)
  File "/usr/local/lib/python2.7/site-packages/stacker/blueprints/base.py", line 365, in resolve_variables
    self.name
  File "/usr/local/lib/python2.7/site-packages/stacker/blueprints/base.py", line 196, in resolve_variable
    raise ValidatorError(var_name, validator.__name__, value, exc)
UnboundLocalError: local variable 'value' referenced before assignment
```
So, it seems SomeVar is undefined, rather than defined as being the empty string is what I was trying to achieve. Passing `-e SomeVar=""` has the same outcome.

It really should be possible to specify that a variable is the empty string at the command line, I think.

**Comment by jonathanunderwood** [comment]
The way to work around this appears to be to use `-e SomeVar=\"\"` which I suppose is logical. I do wonder if there's a nicer fix possible, but I can also see why this might not be considered a bug :)

**Comment by ttaub** [comment]
Thanks for letting us know. 

This is the default behavior for how our command line argument parsing works, so I don't think the fix will be very trivial. I think it's best to leave it as is for now.

If this is a serious issue for you, feel free to submit a PR and I will take a look at it.

**Comment by jonathanunderwood** [comment]
Yes - I think I agree, I can't see a simple way to "fix" this. Actually, I'm not sure it's broken, in fact. Will close.
