### ISSUE TITLE
Issue with Diff-ing stacks

### ISSUE THREAD

**Issue by Roberttmoon** [remind101/stacker#343]
I tired to diff some stacks that worked in 0.8.6 in Stacker 1.0, and revived this error.

stacktrace: 
```Traceback (most recent call last):
  File "/home/rmoon/Documents/git/[redacted]/venv/bin/stacker", line 9, in <module>
    args.run(args)
  File "/home/rmoon/Documents/git/[redacted]/venv/local/lib/python2.7/site-packages/stacker/commands/stacker/diff.py", line 32, in run
    action.execute()
  File "/home/rmoon/Documents/git/[redacted]/venv/local/lib/python2.7/site-packages/stacker/actions/base.py", line 124, in execute
    self.run(*args, **kwargs)
  File "/home/rmoon/Documents/git/[redacted]/venv/local/lib/python2.7/site-packages/stacker/actions/diff.py", line 203, in run
    plan.execute()
  File "/home/rmoon/Documents/git/[redacted]/venv/local/lib/python2.7/site-packages/stacker/plan.py", line 267, in execute
    if not self._single_run():
  File "/home/rmoon/Documents/git/[redacted]/venv/local/lib/python2.7/site-packages/stacker/plan.py", line 227, in _single_run
    status = step.run()
  File "/home/rmoon/Documents/git/[redacted]/venv/local/lib/python2.7/site-packages/stacker/plan.py", line 74, in run
    return self._run_func(self.stack, status=self.status)
  File "/home/rmoon/Documents/git/[redacted]/venv/local/lib/python2.7/site-packages/stacker/actions/diff.py", line 169, in _diff_stack
    parameters = self.build_parameters(stack)
TypeError: build_parameters() takes exactly 3 arguments (2 given)
```

Thanks for your time, and Stacker is awesome!

Robert

**Comment by mchristen** [comment]
@Roberttmoon I also ran into this problem, but I just submitted a quick fix for this in PR #344. Feel free to try out that branch and see if the fix works for you.
