### ISSUE TITLE
Traceback when TroposphereType creation fails 

### ISSUE THREAD

**Issue by danielkza** [remind101/stacker#377]
Instead of getting a nice validation error message when creating a Troposphere resource fails, I get the following traceback:

Using stacker 1.0.1.

```
Traceback (most recent call last):
  File "venv/bin/stacker", line 9, in <module>
    args.run(args)
  File "venv/lib/python2.7/site-packages/stacker/commands/stacker/build.py", line 52, in run
    dump=options.dump)
  File "venv/lib/python2.7/site-packages/stacker/actions/base.py", line 124, in execute
    self.run(*args, **kwargs)
  File "venv/lib/python2.7/site-packages/stacker/actions/build.py", line 288, in run
    plan.dump(directory=dump, context=self.context)
  File "venv/lib/python2.7/site-packages/stacker/plan.py", line 323, in dump
    provider=None,
  File "venv/lib/python2.7/site-packages/stacker/stack.py", line 154, in resolve
    self.blueprint.resolve_variables(self.variables)
  File "venv/lib/python2.7/site-packages/stacker/blueprints/base.py", line 438, in resolve_variables
    self.name
  File "venv/lib/python2.7/site-packages/stacker/blueprints/base.py", line 217, in resolve_variable
    value = validate_variable_type(var_name, var_type, value)
  File "venv/lib/python2.7/site-packages/stacker/blueprints/base.py", line 133, in validate_variable_type
    name = "{}.create".format(var_type.resource_name)
AttributeError: 'TroposphereType' object has no attribute 'resource_name'
```

**Comment by danielkza** [comment]
Additionally, it seems TroposphereType arguments cannot be lists, as the dict keys are used as titles. But titles are optional - they can be just set to None when calling `from_dict`.

**Comment by phobologic** [comment]
Hey @danielkza - can you share a stacker config/blueprint that fails in the way you mention here?

**Comment by danielkza** [comment]
I believe the TroposphereType rework might have fixed this already.

**Comment by phobologic** [comment]
Awesome - I'll let you close it if you feel comfortable with that, or if you get a chance to validate it.  Thanks!

**Comment by phobologic** [comment]
@danielkza I'm going to go ahead and close this - if you run into it again, please feel free to re-open!  Thanks.
