### ISSUE TITLE
stacker build without defining a variable referenced in yaml produces `UnboundLocalError` error without much info

### ISSUE THREAD

**Issue by GarisonLotus** [remind101/stacker#387]
The `UnboundLocalError` is actually the intended behavior here and most of us would never run into this... However this standard error means nothing to someone who doesn't know python, not familiar with standard python errors, or is not able to dig into the code. A nicer error would be l nice. This issue is here so we can make this error a little nicer for someone launching a blueprint and yaml, but forgetting to set a variable. 

Actual message received: 
15:21:55 UnboundLocalError: local variable 'value' referenced before assignment

To reproduce:  Just do a stacker build and forget to set a variable referenced. 
Stack Trace to help find where to catch this: Attached... but here is a good start: base.py, line 214, in resolve_variable

[UnboundLocalError_trace.txt](https://github.com/remind101/stacker/files/1006100/UnboundLocalError_trace.txt)

**Comment by phobologic** [comment]
```
Traceback (most recent call last):
  File "/app/jenkins/workspace/OPS_Provision-hosts-stacker-c3-equivalent_Build/venv/bin/stacker", line 9, in <module>
    args.run(args)
  File "/app/jenkins/workspace/OPS_Provision-hosts-stacker-c3-equivalent_Build/venv/lib/python2.7/site-packages/stacker/commands/stacker/build.py", line 52, in run
    dump=options.dump)
  File "/app/jenkins/workspace/OPS_Provision-hosts-stacker-c3-equivalent_Build/venv/lib/python2.7/site-packages/stacker/actions/base.py", line 124, in execute
    self.run(*args, **kwargs)
  File "/app/jenkins/workspace/OPS_Provision-hosts-stacker-c3-equivalent_Build/venv/lib/python2.7/site-packages/stacker/actions/build.py", line 283, in run
    plan.execute()
  File "/app/jenkins/workspace/OPS_Provision-hosts-stacker-c3-equivalent_Build/venv/lib/python2.7/site-packages/stacker/plan.py", line 267, in execute
    if not self._single_run():
  File "/app/jenkins/workspace/OPS_Provision-hosts-stacker-c3-equivalent_Build/venv/lib/python2.7/site-packages/stacker/plan.py", line 227, in _single_run
    status = step.run()
  File "/app/jenkins/workspace/OPS_Provision-hosts-stacker-c3-equivalent_Build/venv/lib/python2.7/site-packages/stacker/plan.py", line 74, in run
    return self._run_func(self.stack, status=self.status)
  File "/app/jenkins/workspace/OPS_Provision-hosts-stacker-c3-equivalent_Build/venv/lib/python2.7/site-packages/stacker/actions/build.py", line 209, in _launch_stack
    stack.resolve(self.context, self.provider)
  File "/app/jenkins/workspace/OPS_Provision-hosts-stacker-c3-equivalent_Build/venv/lib/python2.7/site-packages/stacker/stack.py", line 154, in resolve
    self.blueprint.resolve_variables(self.variables)
  File "/app/jenkins/workspace/OPS_Provision-hosts-stacker-c3-equivalent_Build/venv/lib/python2.7/site-packages/stacker/blueprints/base.py", line 438, in resolve_variables
    self.name
  File "/app/jenkins/workspace/OPS_Provision-hosts-stacker-c3-equivalent_Build/venv/lib/python2.7/site-packages/stacker/blueprints/base.py", line 214, in resolve_variable
    raise ValidatorError(var_name, validator.__name__, value, exc)
UnboundLocalError: local variable 'value' referenced before assignment
```

Just adding this here - it's the contents of the trace file @GarisonLotus provided.

**Comment by GarisonLotus** [comment]
ok, so I did a little digging to look into this more and found out this is not the problem I originally thought.  I tried spinning up the regular bastion.py from stacker_blueprints and got this when I tried to forget to define a variable in the yaml:

Error with variable key missing from yaml:

> stacker.exceptions.MissingVariable: Variable "OfficeNetwork" in blueprint "forgetting-variable-test" is missing

That's a good error message. So I moved on. Then I tried it by doing what the user claimed, which was to set it to a non defined variable: 

> stacker.exceptions.MissingEnvironment: Environment missing key notdefined.

Also expected, and not the behavior reported. So far, everything went as I expected, so I went back digging into jenkins to find out what actions the User who ran into this issue performed and found out that they DID set the variable, they just set it as blank via a `-e variable=`. So I instead put the variable key in the yaml with no value and Voilà...

Variable key set with value blank in yaml:

> UnboundLocalError: local variable 'value' referenced before assignment


Below is my yaml for this little test:

```
sys_path: ./

mappings:
  AmiMap:
    us-east-1:
      NAT: ami-ad227cc4
      ubuntu1404: ami-74e27e1c
      bastion: ami-74e27e1c
    us-west-2:
      NAT: ami-290f4119
      ubuntu1404: ami-5189a661
      bastion: ami-5189a661

stacks:
  - name: forgetting-variable-test
    class_path: stacker_blueprints.bastion.Bastion
    variables:
      VpcId: vpc-5e9f913b
      DefaultSG: sg-f7674d91
      PublicSubnets: subnet-497c602c, subnet-b61928c1
      PrivateSubnets: subnet-487c602d, subnet-b51928c2
      AvailabilityZones: us-west-2a,us-west-2b
      InstanceType: c4.large
      MinSize: "1"
      MaxSize: "5"
      OfficeNetwork:
      SshKeyName: garison_sturdylab
      ImageName: bastion

```
