### ISSUE TITLE
Potential regression in #413 - Previous stacker template bucket created in us-east-1 no longer usable if deploying into any other region

### ISSUE THREAD

**Issue by GarisonLotus** [remind101/stacker#416]
In testing my PR, I think I found a regression in matser from PR 413.   I had a bucket in us-east-1 that has my templates.  This bucket already existed since I had been using stacker. When Stacker build calls the CreateStack CFN operation, boto is rejecting the request due to the templateurl being incorrectly set (or something like that... I have not looked at the code yet).

This is what I ran, into us-east-2 with my template bucket being in-us-east-1:

```
⇒  stacker build sturdylab.env sturdylab.yaml -r us-east-2
[2017-06-23T11:10:38] Using Default AWS Provider
[2017-06-23T11:10:38] Executing pre_build hooks: stacker.hooks.aws_lambda.upload_lambda_functions
[2017-06-23T11:10:38] lambda: using custom bucket: sturdylab-stacker-artifacts-us-east-2-test
[2017-06-23T11:10:38] lambda: using bucket region from stacker session: us-east-2
[2017-06-23T11:10:38] Creating bucket sturdylab-stacker-artifacts-us-east-2-test in us-east-2
[2017-06-23T11:10:39] lambda: base directory: /Users/garison/Development/sturdy-stacker-awslimitchecker/stacker/modules/awslimitchecker-lambda
[2017-06-23T11:10:39] lambda: adding 1894 files:
[2017-06-23T11:10:49] lambda: uploading object lambda-awslimitchecker-69217ca3238e83359245f99f97ac775e.zip
[2017-06-23T11:10:52] Plan Status:
[2017-06-23T11:10:52] 	sturdylab-awslimitchecker: pending
Traceback (most recent call last):
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/bin/stacker", line 9, in <module>
    args.run(args)
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/lib/python2.7/site-packages/stacker/commands/stacker/build.py", line 52, in run
    dump=options.dump)
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/lib/python2.7/site-packages/stacker/actions/base.py", line 185, in execute
    self.run(*args, **kwargs)
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/lib/python2.7/site-packages/stacker/actions/build.py", line 283, in run
    plan.execute()
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/lib/python2.7/site-packages/stacker/plan.py", line 267, in execute
    if not self._single_run():
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/lib/python2.7/site-packages/stacker/plan.py", line 227, in _single_run
    status = step.run()
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/lib/python2.7/site-packages/stacker/plan.py", line 74, in run
    return self._run_func(self.stack, status=self.status)
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/lib/python2.7/site-packages/stacker/actions/build.py", line 221, in _launch_stack
    tags)
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/lib/python2.7/site-packages/stacker/providers/aws/default.py", line 219, in create_stack
    Capabilities=["CAPABILITY_NAMED_IAM"]),
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/lib/python2.7/site-packages/stacker/providers/aws/default.py", line 71, in retry_on_throttling
    retry_checker=_throttling_checker)
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/lib/python2.7/site-packages/stacker/util.py", line 59, in retry_with_backoff
    return function(*args, **kwargs)
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/garison/Development/enviornments/GarisonLotus-stacker/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStack operation: TemplateURL must reference a valid S3 object to which you have access.
```

**Comment by phobologic** [comment]
Fixed in #417
