### ISSUE TITLE
Clean up error when missing stack config values

### ISSUE THREAD

**Issue by phobologic** [remind101/stacker#424]
This could be better:

```
Traceback (most recent call last):
  File "/venv/413/bin/stacker", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/remind/repos/stacker/scripts/stacker", line 9, in <module>
    args.run(args)
  File "/remind/repos/stacker/stacker/commands/stacker/build.py", line 52, in run
    dump=options.dump)
  File "/remind/repos/stacker/stacker/actions/base.py", line 127, in execute
    self.run(*args, **kwargs)
  File "/remind/repos/stacker/stacker/actions/build.py", line 283, in run
    plan.execute()
  File "/remind/repos/stacker/stacker/plan.py", line 267, in execute
    if not self._single_run():
  File "/remind/repos/stacker/stacker/plan.py", line 227, in _single_run
    status = step.run()
  File "/remind/repos/stacker/stacker/plan.py", line 74, in run
    return self._run_func(self.stack, status=self.status)
  File "/remind/repos/stacker/stacker/actions/build.py", line 209, in _launch_stack
    stack.resolve(self.context, self.provider)
  File "/remind/repos/stacker/stacker/stack.py", line 154, in resolve
    self.blueprint.resolve_variables(self.variables)
  File "/remind/repos/stacker/stacker/stack.py", line 110, in blueprint
    class_path = self.definition["class_path"]
KeyError: 'class_path'
```

**Comment by ejholmes** [comment]
This is better after https://github.com/remind101/stacker/pull/443.

It still raises an exception, but shows you specifically what stack has the problem.
