### ISSUE TITLE
`stacker info` fails with traceback

### ISSUE THREAD

**Issue by danielkza** [remind101/stacker#428]
Using newly released stacker 1.0.3 (rev 60694300bc05c2c1).

```bash
$ stacker info env config.yml
Traceback (most recent call last):
  File "/home/danielkza/cobli/deploy/cloudformation/venv/bin/stacker", line 8, in <module>
    stacker.configure(args)
  File "/home/danielkza/cobli/deploy/cloudformation/venv/lib/python2.7/site-packages/stacker/commands/stacker/__init__.py", line 24, in configure
    super(Stacker, self).configure(options, **kwargs)
  File "/home/danielkza/cobli/deploy/cloudformation/venv/lib/python2.7/site-packages/stacker/commands/stacker/base.py", line 105, in configure
    tail=options.tail)
AttributeError: 'Namespace' object has no attribute 'tail'
```

**Comment by phobologic** [comment]
Should be fixed in 1.0.4 (just released) - thanks @danielkza
