### ISSUE TITLE
Build with --dump option fails to create intermediate directories

### ISSUE THREAD

**Issue by danielkza** [remind101/stacker#498]
Using stacker 1.1.1, trying to dump a multi-stack config run fails with the following traceback:

```
[2017-10-24T16:09:40] Using default AWS provider mode
[2017-10-24T16:09:41] Dumping "Create/Update stacks"...
[2017-10-24T16:09:41] Writing stack "cobli-cassandra-sns" -> dump/stack_templates/cobli-cassandra-sns/sns-5d0ce3ca.json
[2017-10-24T16:09:43] Writing stack "cobli-cassandra-asg" -> dump/stack_templates/cobli-cassandra-asg/asg-bd6d7f66.json
Traceback (most recent call last):
  File "deploy/cloudformation/cloudform-venv/bin/stacker", line 9, in <module>
    args.run(args)
  File "deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/stacker/commands/stacker/build.py", line 46, in run
    dump=options.dump)
  File "deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/stacker/actions/base.py", line 131, in execute
    self.run(*args, **kwargs)
  File "deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/stacker/actions/build.py", line 365, in run
    provider=self.provider)
  File "deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/stacker/plan.py", line 359, in dump
    with open(path, "w") as f:
IOError: [Errno 2] No such file or directory: u'dump/stack_templates/cobli-cassandra-asg/asg-bd6d7f66.json'
```

**Comment by shakerky** [comment]
Adding some debugging into /usr/local/lib/python2.7/site-packages/stacker/plan.py:
[2017-10-26T15:41:54] directory: ./dump
[2017-10-26T15:41:54] filename: stack_templates/vpc-dev-01-vpc/vpc-a968b133.json

It does the os.makedirs on 'directory', then open on directory/filename
