### ISSUE TITLE
Tail (-t) breaks if aws spend more than 5 seconds to start the stack.

### ISSUE THREAD

**Issue by Evnsan** [remind101/stacker#515]
Hey folks, I am facing this problem when trying to deploy a stack with asg and codedeploy. Do you think it's a big deal?

```
[2017-11-29T15:10:55] Tailing stack: alb-test-1-app
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/evnsan/git/cobli/deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/stacker/providers/aws/default.py", line 541, in tail_stack
    self.tail_stack(stack, retries=retries + 1, **kwargs)
  File "/home/evnsan/git/cobli/deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/stacker/providers/aws/default.py", line 541, in tail_stack
    self.tail_stack(stack, retries=retries + 1, **kwargs)
  File "/home/evnsan/git/cobli/deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/stacker/providers/aws/default.py", line 541, in tail_stack
    self.tail_stack(stack, retries=retries + 1, **kwargs)
  File "/home/evnsan/git/cobli/deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/stacker/providers/aws/default.py", line 541, in tail_stack
    self.tail_stack(stack, retries=retries + 1, **kwargs)
  File "/home/evnsan/git/cobli/deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/stacker/providers/aws/default.py", line 541, in tail_stack
    self.tail_stack(stack, retries=retries + 1, **kwargs)
  File "/home/evnsan/git/cobli/deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/stacker/providers/aws/default.py", line 535, in tail_stack
    include_initial=False)
  File "/home/evnsan/git/cobli/deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/stacker/providers/aws/default.py", line 577, in tail
    initial_events = self.get_events(stack_name)
  File "/home/evnsan/git/cobli/deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/stacker/providers/aws/default.py", line 562, in get_events
    StackName=stackname
  File "/home/evnsan/git/cobli/deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/evnsan/git/cobli/deploy/cloudformation/cloudform-venv/local/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (ValidationError) when calling the DescribeStackEvents operation: Stack [alb-test-1-app] does not exist
```

stacker/providers/aws/default.py:
```
 24 MAX_TAIL_RETRIES = 5
.
.
.
532         try:                                                                    
533             self.tail(stack.fqn,                                                
534                       log_func=log_func,                                        
535                       include_initial=False)                                    
536         except botocore.exceptions.ClientError as e:                            
537             if "does not exist" in e.message and retries < MAX_TAIL_RETRIES:    
538                 # stack might be in the process of launching, wait for a second 
539                 # and try again                                                 
540                 time.sleep(1)                                                   
541                 self.tail_stack(stack, retries=retries + 1, **kwargs)           
542             else:                                                               
543                 raise
```

**Comment by phobologic** [comment]
Hey @Evnsan - sorry for the delay in getting back to you, the re:Invent + the holidays took up a lot of my focus.  This does seem like an issue, though honestly I'm not sure what the solution is.  We could increase the # of retries it allows, though I'm not sure what the right balance is.

To be honest, we rarely (hardly ever) use `--tail` at Remind, so I'd love a little guidance on what you (and others who do use it) believe would be the best behavior here.  Thanks!

**Comment by ajk8** [comment]
I use it all the time. It is very nice to see the events as they flow past. My 2c: retry every 5 seconds instead of every 1, and keep the number of retries at 5. I think the 1-second loop is unnecessary, and there's no need to spend your API limits on that.

On a related note, this exception now occurs (as of 1.2.0) when a stack is in a completed teardown state. So, if a stack is skipped because it didn't exist, the exception will show up. If you just reach the end of the tail on a destroy operation, the exception will show up. I've been in the code trying to figure out where to catch these issues, but no joy yet. Hopefully someone with deeper knowledge of the code can work it out pretty quickly. I think I'm going to have to downgrade for now.

**Comment by phobologic** [comment]
@ajk8 can you give 1.3 a try and let me know if you see the same issue?  A lot of changes have been made around this code, so hopefully you won't be running into the issue as much any longer.
