### ISSUE TITLE
AWS throttling API responses should be retried

### ISSUE THREAD

**Issue by berndtj** [remind101/stacker#54]
Stacker exits upon hitting an AWS throttling response.  I would expect the request to be retried (perhaps after a brief back-off):

```python
Traceback (most recent call last):
  File "/usr/local/bin/stacker", line 145, in <module>
    builder.build(stack_definitions)
  File "/usr/local/lib/python2.7/dist-packages/stacker/builder.py", line 368, in build
    self.launch_stack(stack_name, blueprint)
  File "/usr/local/lib/python2.7/dist-packages/stacker/builder.py", line 264, in launch_stack
    stack = self.get_stack(full_name)
  File "/usr/local/lib/python2.7/dist-packages/stacker/builder.py", line 212, in get_stack
    return self.conn.cloudformation.describe_stacks(stack_full_name)[0]
  File "/usr/lib/python2.7/dist-packages/boto/cloudformation/connection.py", line 655, in describe_stacks
    return self.get_list('DescribeStacks', params, [('member', Stack)])
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 1182, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>Throttling</Code>
    <Message>Rate exceeded</Message>
  </Error>
  <RequestId>f9428caa-39ff-11e5-bb46-05293e3ea2eb</RequestId>
</ErrorResponse>
```

**Comment by phobologic** [comment]
So this is a little annoying, since boto actually handles throttling internally - provided all the APIs were consistent and returned a 50X (I think it's 503), but for some reason it looks like CloudFormation uses a 400.

**Comment by phobologic** [comment]
Ahh, looks like it's only for certain services.
