### ISSUE TITLE
Setting stack policy breaks when stack has tags?

### ISSUE THREAD

**Issue by ejholmes** [remind101/stacker#577]
Saw this happen when adding a `tags` section to a stack config:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/stacker-1.2.0-py2.7.egg/stacker/plan.py", line 89, in _run_once
    status = self.fn(self.stack, status=self.status)
  File "/usr/local/lib/python2.7/site-packages/stacker-1.2.0-py2.7.egg/stacker/actions/build.py", line 311, in _launch_stack
    stack_policy=stack_policy,
  File "/usr/local/lib/python2.7/site-packages/stacker-1.2.0-py2.7.egg/stacker/providers/aws/default.py", line 798, in update_stack
    stack_policy=stack_policy, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/stacker-1.2.0-py2.7.egg/stacker/providers/aws/default.py", line 848, in interactive_update_stack
    self.cloudformation.set_stack_policy(args)
  File "/usr/local/lib/python2.7/site-packages/botocore-1.9.15-py2.7.egg/botocore/client.py", line 312, in _api_call
    "%s() only accepts keyword arguments." % py_operation_name)
TypeError: set_stack_policy() only accepts keyword arguments.
```

**Comment by ejholmes** [comment]
Fixed in #588.
