### ISSUE TITLE
Need to handle ROLLBACK messages better

### ISSUE THREAD

**Issue by phobologic** [remind101/stacker#8]
While rolling out an RDS stack had an issue - it rolled back, but it totally crashed the builder:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "build/bdist.macosx-10.10-intel/egg/stacker/builder.py", line 349, in build
    self.launch_stack(stack_name, template)
  File "build/bdist.macosx-10.10-intel/egg/stacker/builder.py", line 276, in launch_stack
    capabilities=['CAPABILITY_IAM'])
  File "/Users/mike/venv/stacker/lib/python2.7/site-packages/boto/cloudformation/connection.py", line 527, in update_stack
    body = self._do_request('UpdateStack', params, '/', 'POST')
  File "/Users/mike/venv/stacker/lib/python2.7/site-packages/boto/cloudformation/connection.py", line 295, in _do_request
    raise self.ResponseError(response.status, response.reason, body=body)
BotoServerError: BotoServerError: 400 Bad Request
{"Error":{"Code":"ValidationError","Message":"Stack:arn:aws:cloudformation:us-east-1:427009882155:stack/mike-remind-com-empireDB/6fdbeba0-c2cf-11e4-9ca6-500150b34c44 is in ROLLBACK_COMPLETE state and can not be updated.","Type":"Sender"},"RequestId":"86377e96-c2cf-11e4-839d-5f31d7b681dd"}
```

**Comment by phobologic** [comment]
Fixed in #473
